### ISSUE TITLE
Add proper userSettings object

### ISSUE THREAD

**Issue by Markionium** [dhis2/d2#44] opened 2015-10-02 19:40 UTC
Currently the only userSetting that is loaded is the `keyUiLocale`

We should probably have a proper UserSettings object where settings can be queried.

One additional one that should be loaded up front is the userStyle as that is required for the headerbar/ui styling

**Comment by adhbh** [comment] 2016-04-17 11:03
@Markionium @nicolayr 
Possible duplicate issues?  https://github.com/dhis2/d2/issues/72 . Do we still need userStyle to be uploaded upfront?

**Comment by nicolayr** [comment] 2016-04-18 23:02
Since all user settings can be fetched from the API with one query now (it wasn't before), it's no longer necessary to treat `userStyle` (which has been renamed to `keyStyle`) in a special way.

And yes, this is definitely a duplicate of #72 - so I'm closing this one :)

**Closed by nicolayr** 2016-04-18 23:02 UTC
Labels: core, duplicate, user
